# Generated by Django 4.1.7 on 2023-12-08 12:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('countapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='license_expiration',
        ),
        migrations.RemoveField(
            model_name='resolutions',
            name='progress',
        ),
        migrations.AlterField(
            model_name='resolutions',
            name='categories',
            field=models.CharField(blank=True, help_text='Enter categories related to the resolution.', max_length=100),
        ),
        migrations.AlterField(
            model_name='resolutions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Automatically set to the creation date and time.'),
        ),
        migrations.AlterField(
            model_name='resolutions',
            name='created_by',
            field=models.ForeignKey(help_text='Select the user who created the resolution.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resolutions',
            name='description',
            field=models.TextField(help_text='Enter a detailed description of the resolution.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='resolutions',
            name='due_date',
            field=models.DateField(blank=True, help_text='Enter the due date of the resolution.', null=True),
        ),
        migrations.AlterField(
            model_name='resolutions',
            name='notes',
            field=models.TextField(blank=True, help_text='Enter any additional notes for the resolution.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='resolutions',
            name='priority',
            field=models.IntegerField(blank=True, help_text='Enter a value between 1 and 10.', null=True, validators=[django.core.validators.MinValueValidator(1, message='Priority must be at least 1.'), django.core.validators.MaxValueValidator(10, message='Priority must be at most 10.')]),
        ),
        migrations.AlterField(
            model_name='resolutions',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Abandoned', 'Abandoned')], default='In Progress', help_text='Select the status of the resolution. Default is in progress.', max_length=20),
        ),
        migrations.AlterField(
            model_name='resolutions',
            name='title',
            field=models.CharField(help_text='Enter the title of the resolution.', max_length=100),
        ),
        migrations.AlterField(
            model_name='resolutions',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Automatically set to the last update date and time.'),
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the news or article.', max_length=100)),
                ('content', models.TextField(help_text='Enter the content of the news or article.')),
                ('image', models.ImageField(blank=True, help_text='Upload an image for the news or article.', null=True, upload_to='news_images/')),
                ('url_link', models.URLField(blank=True, help_text='Enter the URL link related to the news or article.')),
                ('categories', models.CharField(blank=True, help_text='Enter categories related to the news or article.', max_length=100)),
                ('tags', models.CharField(blank=True, help_text='Enter tags related to the news or article.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Automatically set to the creation date and time.')),
                ('created_by', models.ForeignKey(help_text='Select the user who created the news or article.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'News and Articles',
                'ordering': ('-created_at',),
            },
        ),
    ]
